name: "multi event pipeline" #event name

on:
    push:
        branches:
            - master
            - test

    pull_request:
        branches:
            - master
    workflow_dispatch:        
jobs:
    # job 1
    on-push:      #job name
        if: github.event_name == 'push'
        runs-on: ubuntu-latest
        steps:    #steop no 1
            - name: "Running on master push"
              run: echo "running on master push"

    # job 2
    on-pull-request:
        if: github.event_name == 'pull_request'
        runs-on: ubuntu-latest
        steps:
            - name: "Running on pull request"
              run: echo "running on pull request"

            # job 3
    on-workflow-disptach:
        if: github.event_name == 'workflow_dispatch'
        runs-on: ubuntu-latest
        steps:
            - name: "Running on workflow dispatch"
              run: echo "running on workflow dispatch"